name: docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up environment
      run: |
        git config --global user.email "test@github.land"
        git config --global user.name "GitHub Almighty"
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[devel]
    - name: Build docs
      run: |
        make -C docs html
    - name: Setup Pages
      if: github.ref_name == 'main'
      uses: actions/configure-pages@v5
    - name: Upload Pages artifact
      if: github.ref_name == 'main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: "docs/build/html"
  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      id: deployment
